//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntroEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersListesiRaporla
    {
        public int OgrenciNo { get; set; }
        public string ogrenciAdi { get; set; }
        public string ogrenciSoyadi { get; set; }
        public int dersID { get; set; }
        public string dersAdi { get; set; }
        public string ogretimElemaniAdi { get; set; }
        public string ogretimElemaniSoyadi { get; set; }
    }
}
