//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntroEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Derskaydi
    {
        public int id { get; set; }
        public Nullable<int> ogrenciID { get; set; }
        public Nullable<int> dersID { get; set; }
        public System.DateTime dersKayitTarihi { get; set; }
        public string durum { get; set; }
    
        public virtual Ders Ders { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
