//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntroEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgretimElemani
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OgretimElemani()
        {
            this.Ders = new HashSet<Ders>();
        }
    
        public int ogretimElemaniID { get; set; }
        public string ogretimElemaniAdi { get; set; }
        public string ogretimElemaniSoyadi { get; set; }
        public string unvan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ders> Ders { get; set; }
    }
}
